//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated 2020-12-05 10:31
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Spectre.Console
{
    public abstract partial class ProgressSpinner
    {
        private sealed class DotsSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠋",
                    "⠙",
                    "⠹",
                    "⠸",
                    "⠼",
                    "⠴",
                    "⠦",
                    "⠧",
                    "⠇",
                    "⠏",
            };
        }
        private sealed class Dots2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⣾",
                    "⣽",
                    "⣻",
                    "⢿",
                    "⡿",
                    "⣟",
                    "⣯",
                    "⣷",
            };
        }
        private sealed class Dots3Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠋",
                    "⠙",
                    "⠚",
                    "⠞",
                    "⠖",
                    "⠦",
                    "⠴",
                    "⠲",
                    "⠳",
                    "⠓",
            };
        }
        private sealed class Dots4Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠄",
                    "⠆",
                    "⠇",
                    "⠋",
                    "⠙",
                    "⠸",
                    "⠰",
                    "⠠",
                    "⠰",
                    "⠸",
                    "⠙",
                    "⠋",
                    "⠇",
                    "⠆",
            };
        }
        private sealed class Dots5Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠋",
                    "⠙",
                    "⠚",
                    "⠒",
                    "⠂",
                    "⠂",
                    "⠒",
                    "⠲",
                    "⠴",
                    "⠦",
                    "⠖",
                    "⠒",
                    "⠐",
                    "⠐",
                    "⠒",
                    "⠓",
                    "⠋",
            };
        }
        private sealed class Dots6Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠁",
                    "⠉",
                    "⠙",
                    "⠚",
                    "⠒",
                    "⠂",
                    "⠂",
                    "⠒",
                    "⠲",
                    "⠴",
                    "⠤",
                    "⠄",
                    "⠄",
                    "⠤",
                    "⠴",
                    "⠲",
                    "⠒",
                    "⠂",
                    "⠂",
                    "⠒",
                    "⠚",
                    "⠙",
                    "⠉",
                    "⠁",
            };
        }
        private sealed class Dots7Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠈",
                    "⠉",
                    "⠋",
                    "⠓",
                    "⠒",
                    "⠐",
                    "⠐",
                    "⠒",
                    "⠖",
                    "⠦",
                    "⠤",
                    "⠠",
                    "⠠",
                    "⠤",
                    "⠦",
                    "⠖",
                    "⠒",
                    "⠐",
                    "⠐",
                    "⠒",
                    "⠓",
                    "⠋",
                    "⠉",
                    "⠈",
            };
        }
        private sealed class Dots8Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠁",
                    "⠁",
                    "⠉",
                    "⠙",
                    "⠚",
                    "⠒",
                    "⠂",
                    "⠂",
                    "⠒",
                    "⠲",
                    "⠴",
                    "⠤",
                    "⠄",
                    "⠄",
                    "⠤",
                    "⠠",
                    "⠠",
                    "⠤",
                    "⠦",
                    "⠖",
                    "⠒",
                    "⠐",
                    "⠐",
                    "⠒",
                    "⠓",
                    "⠋",
                    "⠉",
                    "⠈",
                    "⠈",
            };
        }
        private sealed class Dots9Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⢹",
                    "⢺",
                    "⢼",
                    "⣸",
                    "⣇",
                    "⡧",
                    "⡗",
                    "⡏",
            };
        }
        private sealed class Dots10Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⢄",
                    "⢂",
                    "⢁",
                    "⡁",
                    "⡈",
                    "⡐",
                    "⡠",
            };
        }
        private sealed class Dots11Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠁",
                    "⠂",
                    "⠄",
                    "⡀",
                    "⢀",
                    "⠠",
                    "⠐",
                    "⠈",
            };
        }
        private sealed class Dots12Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⢀⠀",
                    "⡀⠀",
                    "⠄⠀",
                    "⢂⠀",
                    "⡂⠀",
                    "⠅⠀",
                    "⢃⠀",
                    "⡃⠀",
                    "⠍⠀",
                    "⢋⠀",
                    "⡋⠀",
                    "⠍⠁",
                    "⢋⠁",
                    "⡋⠁",
                    "⠍⠉",
                    "⠋⠉",
                    "⠋⠉",
                    "⠉⠙",
                    "⠉⠙",
                    "⠉⠩",
                    "⠈⢙",
                    "⠈⡙",
                    "⢈⠩",
                    "⡀⢙",
                    "⠄⡙",
                    "⢂⠩",
                    "⡂⢘",
                    "⠅⡘",
                    "⢃⠨",
                    "⡃⢐",
                    "⠍⡐",
                    "⢋⠠",
                    "⡋⢀",
                    "⠍⡁",
                    "⢋⠁",
                    "⡋⠁",
                    "⠍⠉",
                    "⠋⠉",
                    "⠋⠉",
                    "⠉⠙",
                    "⠉⠙",
                    "⠉⠩",
                    "⠈⢙",
                    "⠈⡙",
                    "⠈⠩",
                    "⠀⢙",
                    "⠀⡙",
                    "⠀⠩",
                    "⠀⢘",
                    "⠀⡘",
                    "⠀⠨",
                    "⠀⢐",
                    "⠀⡐",
                    "⠀⠠",
                    "⠀⢀",
                    "⠀⡀",
            };
        }
        private sealed class Dots8BitSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠀",
                    "⠁",
                    "⠂",
                    "⠃",
                    "⠄",
                    "⠅",
                    "⠆",
                    "⠇",
                    "⡀",
                    "⡁",
                    "⡂",
                    "⡃",
                    "⡄",
                    "⡅",
                    "⡆",
                    "⡇",
                    "⠈",
                    "⠉",
                    "⠊",
                    "⠋",
                    "⠌",
                    "⠍",
                    "⠎",
                    "⠏",
                    "⡈",
                    "⡉",
                    "⡊",
                    "⡋",
                    "⡌",
                    "⡍",
                    "⡎",
                    "⡏",
                    "⠐",
                    "⠑",
                    "⠒",
                    "⠓",
                    "⠔",
                    "⠕",
                    "⠖",
                    "⠗",
                    "⡐",
                    "⡑",
                    "⡒",
                    "⡓",
                    "⡔",
                    "⡕",
                    "⡖",
                    "⡗",
                    "⠘",
                    "⠙",
                    "⠚",
                    "⠛",
                    "⠜",
                    "⠝",
                    "⠞",
                    "⠟",
                    "⡘",
                    "⡙",
                    "⡚",
                    "⡛",
                    "⡜",
                    "⡝",
                    "⡞",
                    "⡟",
                    "⠠",
                    "⠡",
                    "⠢",
                    "⠣",
                    "⠤",
                    "⠥",
                    "⠦",
                    "⠧",
                    "⡠",
                    "⡡",
                    "⡢",
                    "⡣",
                    "⡤",
                    "⡥",
                    "⡦",
                    "⡧",
                    "⠨",
                    "⠩",
                    "⠪",
                    "⠫",
                    "⠬",
                    "⠭",
                    "⠮",
                    "⠯",
                    "⡨",
                    "⡩",
                    "⡪",
                    "⡫",
                    "⡬",
                    "⡭",
                    "⡮",
                    "⡯",
                    "⠰",
                    "⠱",
                    "⠲",
                    "⠳",
                    "⠴",
                    "⠵",
                    "⠶",
                    "⠷",
                    "⡰",
                    "⡱",
                    "⡲",
                    "⡳",
                    "⡴",
                    "⡵",
                    "⡶",
                    "⡷",
                    "⠸",
                    "⠹",
                    "⠺",
                    "⠻",
                    "⠼",
                    "⠽",
                    "⠾",
                    "⠿",
                    "⡸",
                    "⡹",
                    "⡺",
                    "⡻",
                    "⡼",
                    "⡽",
                    "⡾",
                    "⡿",
                    "⢀",
                    "⢁",
                    "⢂",
                    "⢃",
                    "⢄",
                    "⢅",
                    "⢆",
                    "⢇",
                    "⣀",
                    "⣁",
                    "⣂",
                    "⣃",
                    "⣄",
                    "⣅",
                    "⣆",
                    "⣇",
                    "⢈",
                    "⢉",
                    "⢊",
                    "⢋",
                    "⢌",
                    "⢍",
                    "⢎",
                    "⢏",
                    "⣈",
                    "⣉",
                    "⣊",
                    "⣋",
                    "⣌",
                    "⣍",
                    "⣎",
                    "⣏",
                    "⢐",
                    "⢑",
                    "⢒",
                    "⢓",
                    "⢔",
                    "⢕",
                    "⢖",
                    "⢗",
                    "⣐",
                    "⣑",
                    "⣒",
                    "⣓",
                    "⣔",
                    "⣕",
                    "⣖",
                    "⣗",
                    "⢘",
                    "⢙",
                    "⢚",
                    "⢛",
                    "⢜",
                    "⢝",
                    "⢞",
                    "⢟",
                    "⣘",
                    "⣙",
                    "⣚",
                    "⣛",
                    "⣜",
                    "⣝",
                    "⣞",
                    "⣟",
                    "⢠",
                    "⢡",
                    "⢢",
                    "⢣",
                    "⢤",
                    "⢥",
                    "⢦",
                    "⢧",
                    "⣠",
                    "⣡",
                    "⣢",
                    "⣣",
                    "⣤",
                    "⣥",
                    "⣦",
                    "⣧",
                    "⢨",
                    "⢩",
                    "⢪",
                    "⢫",
                    "⢬",
                    "⢭",
                    "⢮",
                    "⢯",
                    "⣨",
                    "⣩",
                    "⣪",
                    "⣫",
                    "⣬",
                    "⣭",
                    "⣮",
                    "⣯",
                    "⢰",
                    "⢱",
                    "⢲",
                    "⢳",
                    "⢴",
                    "⢵",
                    "⢶",
                    "⢷",
                    "⣰",
                    "⣱",
                    "⣲",
                    "⣳",
                    "⣴",
                    "⣵",
                    "⣶",
                    "⣷",
                    "⢸",
                    "⢹",
                    "⢺",
                    "⢻",
                    "⢼",
                    "⢽",
                    "⢾",
                    "⢿",
                    "⣸",
                    "⣹",
                    "⣺",
                    "⣻",
                    "⣼",
                    "⣽",
                    "⣾",
                    "⣿",
            };
        }
        private sealed class LineSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(130);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "-",
                    "\\",
                    "|",
                    "/",
            };
        }
        private sealed class Line2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠂",
                    "-",
                    "–",
                    "—",
                    "–",
                    "-",
            };
        }
        private sealed class PipeSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "┤",
                    "┘",
                    "┴",
                    "└",
                    "├",
                    "┌",
                    "┬",
                    "┐",
            };
        }
        private sealed class SimpleDotsSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(400);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    ".  ",
                    ".. ",
                    "...",
                    "   ",
            };
        }
        private sealed class SimpleDotsScrollingSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(200);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    ".  ",
                    ".. ",
                    "...",
                    " ..",
                    "  .",
                    "   ",
            };
        }
        private sealed class StarSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(70);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "✶",
                    "✸",
                    "✹",
                    "✺",
                    "✹",
                    "✷",
            };
        }
        private sealed class Star2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "+",
                    "x",
                    "*",
            };
        }
        private sealed class FlipSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(70);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "_",
                    "_",
                    "_",
                    "-",
                    "`",
                    "`",
                    "'",
                    "´",
                    "-",
                    "_",
                    "_",
                    "_",
            };
        }
        private sealed class HamburgerSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "☱",
                    "☲",
                    "☴",
            };
        }
        private sealed class GrowVerticalSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▁",
                    "▃",
                    "▄",
                    "▅",
                    "▆",
                    "▇",
                    "▆",
                    "▅",
                    "▄",
                    "▃",
            };
        }
        private sealed class GrowHorizontalSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▏",
                    "▎",
                    "▍",
                    "▌",
                    "▋",
                    "▊",
                    "▉",
                    "▊",
                    "▋",
                    "▌",
                    "▍",
                    "▎",
            };
        }
        private sealed class BalloonSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(140);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    " ",
                    ".",
                    "o",
                    "O",
                    "@",
                    "*",
                    " ",
            };
        }
        private sealed class Balloon2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    ".",
                    "o",
                    "O",
                    "°",
                    "O",
                    "o",
                    ".",
            };
        }
        private sealed class NoiseSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▓",
                    "▒",
                    "░",
            };
        }
        private sealed class BounceSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⠁",
                    "⠂",
                    "⠄",
                    "⠂",
            };
        }
        private sealed class BoxBounceSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▖",
                    "▘",
                    "▝",
                    "▗",
            };
        }
        private sealed class BoxBounce2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▌",
                    "▀",
                    "▐",
                    "▄",
            };
        }
        private sealed class TriangleSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(50);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◢",
                    "◣",
                    "◤",
                    "◥",
            };
        }
        private sealed class ArcSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◜",
                    "◠",
                    "◝",
                    "◞",
                    "◡",
                    "◟",
            };
        }
        private sealed class CircleSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◡",
                    "⊙",
                    "◠",
            };
        }
        private sealed class SquareCornersSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(180);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◰",
                    "◳",
                    "◲",
                    "◱",
            };
        }
        private sealed class CircleQuartersSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◴",
                    "◷",
                    "◶",
                    "◵",
            };
        }
        private sealed class CircleHalvesSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(50);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◐",
                    "◓",
                    "◑",
                    "◒",
            };
        }
        private sealed class SquishSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "╫",
                    "╪",
            };
        }
        private sealed class ToggleSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(250);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⊶",
                    "⊷",
            };
        }
        private sealed class Toggle2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▫",
                    "▪",
            };
        }
        private sealed class Toggle3Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "□",
                    "■",
            };
        }
        private sealed class Toggle4Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "■",
                    "□",
                    "▪",
                    "▫",
            };
        }
        private sealed class Toggle5Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▮",
                    "▯",
            };
        }
        private sealed class Toggle6Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(300);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "ဝ",
                    "၀",
            };
        }
        private sealed class Toggle7Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⦾",
                    "⦿",
            };
        }
        private sealed class Toggle8Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◍",
                    "◌",
            };
        }
        private sealed class Toggle9Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "◉",
                    "◎",
            };
        }
        private sealed class Toggle10Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "㊂",
                    "㊀",
                    "㊁",
            };
        }
        private sealed class Toggle11Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(50);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⧇",
                    "⧆",
            };
        }
        private sealed class Toggle12Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "☗",
                    "☖",
            };
        }
        private sealed class Toggle13Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "=",
                    "*",
                    "-",
            };
        }
        private sealed class ArrowSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "←",
                    "↖",
                    "↑",
                    "↗",
                    "→",
                    "↘",
                    "↓",
                    "↙",
            };
        }
        private sealed class Arrow2Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⬆️ ",
                    "↗️ ",
                    "➡️ ",
                    "↘️ ",
                    "⬇️ ",
                    "↙️ ",
                    "⬅️ ",
                    "↖️ ",
            };
        }
        private sealed class Arrow3Spinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▹▹▹▹▹",
                    "▸▹▹▹▹",
                    "▹▸▹▹▹",
                    "▹▹▸▹▹",
                    "▹▹▹▸▹",
                    "▹▹▹▹▸",
            };
        }
        private sealed class BouncingBarSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "[    ]",
                    "[=   ]",
                    "[==  ]",
                    "[=== ]",
                    "[ ===]",
                    "[  ==]",
                    "[   =]",
                    "[    ]",
                    "[   =]",
                    "[  ==]",
                    "[ ===]",
                    "[====]",
                    "[=== ]",
                    "[==  ]",
                    "[=   ]",
            };
        }
        private sealed class BouncingBallSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "( ●    )",
                    "(  ●   )",
                    "(   ●  )",
                    "(    ● )",
                    "(     ●)",
                    "(    ● )",
                    "(   ●  )",
                    "(  ●   )",
                    "( ●    )",
                    "(●     )",
            };
        }
        private sealed class SmileySpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(200);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "😄 ",
                    "😝 ",
            };
        }
        private sealed class MonkeySpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(300);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "🙈 ",
                    "🙈 ",
                    "🙉 ",
                    "🙊 ",
            };
        }
        private sealed class HeartsSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "💛 ",
                    "💙 ",
                    "💜 ",
                    "💚 ",
                    "❤️ ",
            };
        }
        private sealed class ClockSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "🕛 ",
                    "🕐 ",
                    "🕑 ",
                    "🕒 ",
                    "🕓 ",
                    "🕔 ",
                    "🕕 ",
                    "🕖 ",
                    "🕗 ",
                    "🕘 ",
                    "🕙 ",
                    "🕚 ",
            };
        }
        private sealed class EarthSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(180);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "🌍 ",
                    "🌎 ",
                    "🌏 ",
            };
        }
        private sealed class MaterialSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(17);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "███████▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "████████▁▁▁▁▁▁▁▁▁▁▁▁",
                    "█████████▁▁▁▁▁▁▁▁▁▁▁",
                    "█████████▁▁▁▁▁▁▁▁▁▁▁",
                    "██████████▁▁▁▁▁▁▁▁▁▁",
                    "███████████▁▁▁▁▁▁▁▁▁",
                    "█████████████▁▁▁▁▁▁▁",
                    "██████████████▁▁▁▁▁▁",
                    "██████████████▁▁▁▁▁▁",
                    "▁██████████████▁▁▁▁▁",
                    "▁██████████████▁▁▁▁▁",
                    "▁██████████████▁▁▁▁▁",
                    "▁▁██████████████▁▁▁▁",
                    "▁▁▁██████████████▁▁▁",
                    "▁▁▁▁█████████████▁▁▁",
                    "▁▁▁▁██████████████▁▁",
                    "▁▁▁▁██████████████▁▁",
                    "▁▁▁▁▁██████████████▁",
                    "▁▁▁▁▁██████████████▁",
                    "▁▁▁▁▁██████████████▁",
                    "▁▁▁▁▁▁██████████████",
                    "▁▁▁▁▁▁██████████████",
                    "▁▁▁▁▁▁▁█████████████",
                    "▁▁▁▁▁▁▁█████████████",
                    "▁▁▁▁▁▁▁▁████████████",
                    "▁▁▁▁▁▁▁▁████████████",
                    "▁▁▁▁▁▁▁▁▁███████████",
                    "▁▁▁▁▁▁▁▁▁███████████",
                    "▁▁▁▁▁▁▁▁▁▁██████████",
                    "▁▁▁▁▁▁▁▁▁▁██████████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁████████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁███████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████",
                    "█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
                    "██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
                    "██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
                    "███▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
                    "████▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
                    "█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
                    "█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
                    "██████▁▁▁▁▁▁▁▁▁▁▁▁▁█",
                    "████████▁▁▁▁▁▁▁▁▁▁▁▁",
                    "█████████▁▁▁▁▁▁▁▁▁▁▁",
                    "█████████▁▁▁▁▁▁▁▁▁▁▁",
                    "█████████▁▁▁▁▁▁▁▁▁▁▁",
                    "█████████▁▁▁▁▁▁▁▁▁▁▁",
                    "███████████▁▁▁▁▁▁▁▁▁",
                    "████████████▁▁▁▁▁▁▁▁",
                    "████████████▁▁▁▁▁▁▁▁",
                    "██████████████▁▁▁▁▁▁",
                    "██████████████▁▁▁▁▁▁",
                    "▁██████████████▁▁▁▁▁",
                    "▁██████████████▁▁▁▁▁",
                    "▁▁▁█████████████▁▁▁▁",
                    "▁▁▁▁▁████████████▁▁▁",
                    "▁▁▁▁▁████████████▁▁▁",
                    "▁▁▁▁▁▁███████████▁▁▁",
                    "▁▁▁▁▁▁▁▁█████████▁▁▁",
                    "▁▁▁▁▁▁▁▁█████████▁▁▁",
                    "▁▁▁▁▁▁▁▁▁█████████▁▁",
                    "▁▁▁▁▁▁▁▁▁█████████▁▁",
                    "▁▁▁▁▁▁▁▁▁▁█████████▁",
                    "▁▁▁▁▁▁▁▁▁▁▁████████▁",
                    "▁▁▁▁▁▁▁▁▁▁▁████████▁",
                    "▁▁▁▁▁▁▁▁▁▁▁▁███████▁",
                    "▁▁▁▁▁▁▁▁▁▁▁▁███████▁",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁███████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁███████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
                    "▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁",
            };
        }
        private sealed class MoonSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "🌑 ",
                    "🌒 ",
                    "🌓 ",
                    "🌔 ",
                    "🌕 ",
                    "🌖 ",
                    "🌗 ",
                    "🌘 ",
            };
        }
        private sealed class RunnerSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(140);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "🚶 ",
                    "🏃 ",
            };
        }
        private sealed class PongSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▐⠂       ▌",
                    "▐⠈       ▌",
                    "▐ ⠂      ▌",
                    "▐ ⠠      ▌",
                    "▐  ⡀     ▌",
                    "▐  ⠠     ▌",
                    "▐   ⠂    ▌",
                    "▐   ⠈    ▌",
                    "▐    ⠂   ▌",
                    "▐    ⠠   ▌",
                    "▐     ⡀  ▌",
                    "▐     ⠠  ▌",
                    "▐      ⠂ ▌",
                    "▐      ⠈ ▌",
                    "▐       ⠂▌",
                    "▐       ⠠▌",
                    "▐       ⡀▌",
                    "▐      ⠠ ▌",
                    "▐      ⠂ ▌",
                    "▐     ⠈  ▌",
                    "▐     ⠂  ▌",
                    "▐    ⠠   ▌",
                    "▐    ⡀   ▌",
                    "▐   ⠠    ▌",
                    "▐   ⠂    ▌",
                    "▐  ⠈     ▌",
                    "▐  ⠂     ▌",
                    "▐ ⠠      ▌",
                    "▐ ⡀      ▌",
                    "▐⠠       ▌",
            };
        }
        private sealed class SharkSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(120);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▐|\\____________▌",
                    "▐_|\\___________▌",
                    "▐__|\\__________▌",
                    "▐___|\\_________▌",
                    "▐____|\\________▌",
                    "▐_____|\\_______▌",
                    "▐______|\\______▌",
                    "▐_______|\\_____▌",
                    "▐________|\\____▌",
                    "▐_________|\\___▌",
                    "▐__________|\\__▌",
                    "▐___________|\\_▌",
                    "▐____________|\\▌",
                    "▐____________/|▌",
                    "▐___________/|_▌",
                    "▐__________/|__▌",
                    "▐_________/|___▌",
                    "▐________/|____▌",
                    "▐_______/|_____▌",
                    "▐______/|______▌",
                    "▐_____/|_______▌",
                    "▐____/|________▌",
                    "▐___/|_________▌",
                    "▐__/|__________▌",
                    "▐_/|___________▌",
                    "▐/|____________▌",
            };
        }
        private sealed class DqpbSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => false;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "d",
                    "q",
                    "p",
                    "b",
            };
        }
        private sealed class WeatherSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(100);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "☀️ ",
                    "☀️ ",
                    "☀️ ",
                    "🌤 ",
                    "⛅️ ",
                    "🌥 ",
                    "☁️ ",
                    "🌧 ",
                    "🌨 ",
                    "🌧 ",
                    "🌨 ",
                    "🌧 ",
                    "🌨 ",
                    "⛈ ",
                    "🌨 ",
                    "🌧 ",
                    "🌨 ",
                    "☁️ ",
                    "🌥 ",
                    "⛅️ ",
                    "🌤 ",
                    "☀️ ",
                    "☀️ ",
            };
        }
        private sealed class ChristmasSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(400);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "🌲",
                    "🎄",
            };
        }
        private sealed class GrenadeSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "،   ",
                    "′   ",
                    " ´ ",
                    " ‾ ",
                    "  ⸌",
                    "  ⸊",
                    "  |",
                    "  ⁎",
                    "  ⁕",
                    " ෴ ",
                    "  ⁓",
                    "   ",
                    "   ",
                    "   ",
            };
        }
        private sealed class PointSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(125);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "∙∙∙",
                    "●∙∙",
                    "∙●∙",
                    "∙∙●",
                    "∙∙∙",
            };
        }
        private sealed class LayerSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(150);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "-",
                    "=",
                    "≡",
            };
        }
        private sealed class BetaWaveSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "ρββββββ",
                    "βρβββββ",
                    "ββρββββ",
                    "βββρβββ",
                    "ββββρββ",
                    "βββββρβ",
                    "ββββββρ",
            };
        }
        private sealed class AestheticSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "▰▱▱▱▱▱▱",
                    "▰▰▱▱▱▱▱",
                    "▰▰▰▱▱▱▱",
                    "▰▰▰▰▱▱▱",
                    "▰▰▰▰▰▱▱",
                    "▰▰▰▰▰▰▱",
                    "▰▰▰▰▰▰▰",
                    "▰▱▱▱▱▱▱",
            };
        }
        private sealed class DefaultSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "⣷",
                    "⣯",
                    "⣟",
                    "⡿",
                    "⢿",
                    "⣻",
                    "⣽",
                    "⣾",
            };
        }
        private sealed class AsciiSpinner : ProgressSpinner
        {
            public override TimeSpan Interval => TimeSpan.FromMilliseconds(80);
            public override bool IsUnicode => true;
            public override IReadOnlyList<string> Frames => new List<string>
            {
                    "-",
                    "\\",
                    "|",
                    "/",
                    "-",
                    "\\",
                    "|",
                    "/",
            };
        }

        /// <summary>
        /// Contains all predefined spinners.
        /// </summary>
        public static class Known
        {
            /// <summary>
            /// Gets the "dots" spinner.
            /// </summary>
            public static ProgressSpinner Dots { get; } = new DotsSpinner();
            /// <summary>
            /// Gets the "dots2" spinner.
            /// </summary>
            public static ProgressSpinner Dots2 { get; } = new Dots2Spinner();
            /// <summary>
            /// Gets the "dots3" spinner.
            /// </summary>
            public static ProgressSpinner Dots3 { get; } = new Dots3Spinner();
            /// <summary>
            /// Gets the "dots4" spinner.
            /// </summary>
            public static ProgressSpinner Dots4 { get; } = new Dots4Spinner();
            /// <summary>
            /// Gets the "dots5" spinner.
            /// </summary>
            public static ProgressSpinner Dots5 { get; } = new Dots5Spinner();
            /// <summary>
            /// Gets the "dots6" spinner.
            /// </summary>
            public static ProgressSpinner Dots6 { get; } = new Dots6Spinner();
            /// <summary>
            /// Gets the "dots7" spinner.
            /// </summary>
            public static ProgressSpinner Dots7 { get; } = new Dots7Spinner();
            /// <summary>
            /// Gets the "dots8" spinner.
            /// </summary>
            public static ProgressSpinner Dots8 { get; } = new Dots8Spinner();
            /// <summary>
            /// Gets the "dots9" spinner.
            /// </summary>
            public static ProgressSpinner Dots9 { get; } = new Dots9Spinner();
            /// <summary>
            /// Gets the "dots10" spinner.
            /// </summary>
            public static ProgressSpinner Dots10 { get; } = new Dots10Spinner();
            /// <summary>
            /// Gets the "dots11" spinner.
            /// </summary>
            public static ProgressSpinner Dots11 { get; } = new Dots11Spinner();
            /// <summary>
            /// Gets the "dots12" spinner.
            /// </summary>
            public static ProgressSpinner Dots12 { get; } = new Dots12Spinner();
            /// <summary>
            /// Gets the "dots8Bit" spinner.
            /// </summary>
            public static ProgressSpinner Dots8Bit { get; } = new Dots8BitSpinner();
            /// <summary>
            /// Gets the "line" spinner.
            /// </summary>
            public static ProgressSpinner Line { get; } = new LineSpinner();
            /// <summary>
            /// Gets the "line2" spinner.
            /// </summary>
            public static ProgressSpinner Line2 { get; } = new Line2Spinner();
            /// <summary>
            /// Gets the "pipe" spinner.
            /// </summary>
            public static ProgressSpinner Pipe { get; } = new PipeSpinner();
            /// <summary>
            /// Gets the "simpleDots" spinner.
            /// </summary>
            public static ProgressSpinner SimpleDots { get; } = new SimpleDotsSpinner();
            /// <summary>
            /// Gets the "simpleDotsScrolling" spinner.
            /// </summary>
            public static ProgressSpinner SimpleDotsScrolling { get; } = new SimpleDotsScrollingSpinner();
            /// <summary>
            /// Gets the "star" spinner.
            /// </summary>
            public static ProgressSpinner Star { get; } = new StarSpinner();
            /// <summary>
            /// Gets the "star2" spinner.
            /// </summary>
            public static ProgressSpinner Star2 { get; } = new Star2Spinner();
            /// <summary>
            /// Gets the "flip" spinner.
            /// </summary>
            public static ProgressSpinner Flip { get; } = new FlipSpinner();
            /// <summary>
            /// Gets the "hamburger" spinner.
            /// </summary>
            public static ProgressSpinner Hamburger { get; } = new HamburgerSpinner();
            /// <summary>
            /// Gets the "growVertical" spinner.
            /// </summary>
            public static ProgressSpinner GrowVertical { get; } = new GrowVerticalSpinner();
            /// <summary>
            /// Gets the "growHorizontal" spinner.
            /// </summary>
            public static ProgressSpinner GrowHorizontal { get; } = new GrowHorizontalSpinner();
            /// <summary>
            /// Gets the "balloon" spinner.
            /// </summary>
            public static ProgressSpinner Balloon { get; } = new BalloonSpinner();
            /// <summary>
            /// Gets the "balloon2" spinner.
            /// </summary>
            public static ProgressSpinner Balloon2 { get; } = new Balloon2Spinner();
            /// <summary>
            /// Gets the "noise" spinner.
            /// </summary>
            public static ProgressSpinner Noise { get; } = new NoiseSpinner();
            /// <summary>
            /// Gets the "bounce" spinner.
            /// </summary>
            public static ProgressSpinner Bounce { get; } = new BounceSpinner();
            /// <summary>
            /// Gets the "boxBounce" spinner.
            /// </summary>
            public static ProgressSpinner BoxBounce { get; } = new BoxBounceSpinner();
            /// <summary>
            /// Gets the "boxBounce2" spinner.
            /// </summary>
            public static ProgressSpinner BoxBounce2 { get; } = new BoxBounce2Spinner();
            /// <summary>
            /// Gets the "triangle" spinner.
            /// </summary>
            public static ProgressSpinner Triangle { get; } = new TriangleSpinner();
            /// <summary>
            /// Gets the "arc" spinner.
            /// </summary>
            public static ProgressSpinner Arc { get; } = new ArcSpinner();
            /// <summary>
            /// Gets the "circle" spinner.
            /// </summary>
            public static ProgressSpinner Circle { get; } = new CircleSpinner();
            /// <summary>
            /// Gets the "squareCorners" spinner.
            /// </summary>
            public static ProgressSpinner SquareCorners { get; } = new SquareCornersSpinner();
            /// <summary>
            /// Gets the "circleQuarters" spinner.
            /// </summary>
            public static ProgressSpinner CircleQuarters { get; } = new CircleQuartersSpinner();
            /// <summary>
            /// Gets the "circleHalves" spinner.
            /// </summary>
            public static ProgressSpinner CircleHalves { get; } = new CircleHalvesSpinner();
            /// <summary>
            /// Gets the "squish" spinner.
            /// </summary>
            public static ProgressSpinner Squish { get; } = new SquishSpinner();
            /// <summary>
            /// Gets the "toggle" spinner.
            /// </summary>
            public static ProgressSpinner Toggle { get; } = new ToggleSpinner();
            /// <summary>
            /// Gets the "toggle2" spinner.
            /// </summary>
            public static ProgressSpinner Toggle2 { get; } = new Toggle2Spinner();
            /// <summary>
            /// Gets the "toggle3" spinner.
            /// </summary>
            public static ProgressSpinner Toggle3 { get; } = new Toggle3Spinner();
            /// <summary>
            /// Gets the "toggle4" spinner.
            /// </summary>
            public static ProgressSpinner Toggle4 { get; } = new Toggle4Spinner();
            /// <summary>
            /// Gets the "toggle5" spinner.
            /// </summary>
            public static ProgressSpinner Toggle5 { get; } = new Toggle5Spinner();
            /// <summary>
            /// Gets the "toggle6" spinner.
            /// </summary>
            public static ProgressSpinner Toggle6 { get; } = new Toggle6Spinner();
            /// <summary>
            /// Gets the "toggle7" spinner.
            /// </summary>
            public static ProgressSpinner Toggle7 { get; } = new Toggle7Spinner();
            /// <summary>
            /// Gets the "toggle8" spinner.
            /// </summary>
            public static ProgressSpinner Toggle8 { get; } = new Toggle8Spinner();
            /// <summary>
            /// Gets the "toggle9" spinner.
            /// </summary>
            public static ProgressSpinner Toggle9 { get; } = new Toggle9Spinner();
            /// <summary>
            /// Gets the "toggle10" spinner.
            /// </summary>
            public static ProgressSpinner Toggle10 { get; } = new Toggle10Spinner();
            /// <summary>
            /// Gets the "toggle11" spinner.
            /// </summary>
            public static ProgressSpinner Toggle11 { get; } = new Toggle11Spinner();
            /// <summary>
            /// Gets the "toggle12" spinner.
            /// </summary>
            public static ProgressSpinner Toggle12 { get; } = new Toggle12Spinner();
            /// <summary>
            /// Gets the "toggle13" spinner.
            /// </summary>
            public static ProgressSpinner Toggle13 { get; } = new Toggle13Spinner();
            /// <summary>
            /// Gets the "arrow" spinner.
            /// </summary>
            public static ProgressSpinner Arrow { get; } = new ArrowSpinner();
            /// <summary>
            /// Gets the "arrow2" spinner.
            /// </summary>
            public static ProgressSpinner Arrow2 { get; } = new Arrow2Spinner();
            /// <summary>
            /// Gets the "arrow3" spinner.
            /// </summary>
            public static ProgressSpinner Arrow3 { get; } = new Arrow3Spinner();
            /// <summary>
            /// Gets the "bouncingBar" spinner.
            /// </summary>
            public static ProgressSpinner BouncingBar { get; } = new BouncingBarSpinner();
            /// <summary>
            /// Gets the "bouncingBall" spinner.
            /// </summary>
            public static ProgressSpinner BouncingBall { get; } = new BouncingBallSpinner();
            /// <summary>
            /// Gets the "smiley" spinner.
            /// </summary>
            public static ProgressSpinner Smiley { get; } = new SmileySpinner();
            /// <summary>
            /// Gets the "monkey" spinner.
            /// </summary>
            public static ProgressSpinner Monkey { get; } = new MonkeySpinner();
            /// <summary>
            /// Gets the "hearts" spinner.
            /// </summary>
            public static ProgressSpinner Hearts { get; } = new HeartsSpinner();
            /// <summary>
            /// Gets the "clock" spinner.
            /// </summary>
            public static ProgressSpinner Clock { get; } = new ClockSpinner();
            /// <summary>
            /// Gets the "earth" spinner.
            /// </summary>
            public static ProgressSpinner Earth { get; } = new EarthSpinner();
            /// <summary>
            /// Gets the "material" spinner.
            /// </summary>
            public static ProgressSpinner Material { get; } = new MaterialSpinner();
            /// <summary>
            /// Gets the "moon" spinner.
            /// </summary>
            public static ProgressSpinner Moon { get; } = new MoonSpinner();
            /// <summary>
            /// Gets the "runner" spinner.
            /// </summary>
            public static ProgressSpinner Runner { get; } = new RunnerSpinner();
            /// <summary>
            /// Gets the "pong" spinner.
            /// </summary>
            public static ProgressSpinner Pong { get; } = new PongSpinner();
            /// <summary>
            /// Gets the "shark" spinner.
            /// </summary>
            public static ProgressSpinner Shark { get; } = new SharkSpinner();
            /// <summary>
            /// Gets the "dqpb" spinner.
            /// </summary>
            public static ProgressSpinner Dqpb { get; } = new DqpbSpinner();
            /// <summary>
            /// Gets the "weather" spinner.
            /// </summary>
            public static ProgressSpinner Weather { get; } = new WeatherSpinner();
            /// <summary>
            /// Gets the "christmas" spinner.
            /// </summary>
            public static ProgressSpinner Christmas { get; } = new ChristmasSpinner();
            /// <summary>
            /// Gets the "grenade" spinner.
            /// </summary>
            public static ProgressSpinner Grenade { get; } = new GrenadeSpinner();
            /// <summary>
            /// Gets the "point" spinner.
            /// </summary>
            public static ProgressSpinner Point { get; } = new PointSpinner();
            /// <summary>
            /// Gets the "layer" spinner.
            /// </summary>
            public static ProgressSpinner Layer { get; } = new LayerSpinner();
            /// <summary>
            /// Gets the "betaWave" spinner.
            /// </summary>
            public static ProgressSpinner BetaWave { get; } = new BetaWaveSpinner();
            /// <summary>
            /// Gets the "aesthetic" spinner.
            /// </summary>
            public static ProgressSpinner Aesthetic { get; } = new AestheticSpinner();
            /// <summary>
            /// Gets the "Default" spinner.
            /// </summary>
            public static ProgressSpinner Default { get; } = new DefaultSpinner();
            /// <summary>
            /// Gets the "Ascii" spinner.
            /// </summary>
            public static ProgressSpinner Ascii { get; } = new AsciiSpinner();
        }
    }
}
